version: "3.9"

services:
  database:
    image: postgres
    container_name: database_openet
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=openet
    volumes:
      - pgdata:/data/postgres

  #redis: 
  #  image: redis:alpine
  #  container_name: redis_openet
  #  ports: 
  #    - 6379:6379
#
  #app:
  #  build: .
  #  container_name: back-end_openet
  #  restart: always
  #  ports: 
  #    - 3333:3333
  #  volumes: 
  #    - .:/usr/app
  #  links: 
  #    - database
  #    - redis
  #  depends_on:
  #    - database
  #    - redis



volumes:
  pgdata:
    driver: local